apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: telemetry
  labels:
    app: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:latest
          ports:
            - name: http
              containerPort: 8123
            - name: tcp
              containerPort: 9000
          volumeMounts:
            - name: clickhouse-data
              mountPath: /var/lib/clickhouse
            - name: clickhouse-config
              mountPath: /etc/clickhouse-server/config.d/config.xml
              subPath: config.xml
            - name: clickhouse-users
              mountPath: /etc/clickhouse-server/users.d/users.xml
              subPath: users.xml
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: clickhouse-data
          persistentVolumeClaim:
            claimName: clickhouse-pvc
        - name: clickhouse-config
          configMap:
            name: clickhouse-config
        - name: clickhouse-users
          configMap:
            name: clickhouse-users

---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: telemetry
  labels:
    app: clickhouse
spec:
  ports:
    - name: http
      port: 8123
      targetPort: 8123
    - name: tcp
      port: 9000
      targetPort: 9000
  selector:
    app: clickhouse
