apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-pv
  namespace: telemetry
  labels:
    app: clickhouse
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/clickhouse # This path should exist on the node
