apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-clickhouse-persistence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskmanager-clickhouse-persistence
  template:
    metadata:
      labels:
        app: taskmanager-clickhouse-persistence
    spec:
      containers:
        - name: taskmanager-clickhouse
          image: apache/flink:1.16.0
          command: ["taskmanager"]
          volumeMounts:
            - name: flink-usrlib
              mountPath: /opt/flink/usrlib
      volumes:
        - name: flink-usrlib
          hostPath:
            path: /Users/samarjeetsingh/practice/telemetry-stream-processor/clickhouse-persistence/target

---
apiVersion: v1
kind: Service
metadata:
  name: taskmanager-clickhouse-persistence
spec:
  ports:
    - port: 8092
      targetPort: 8092  # Default taskmanager port for clickhouse
  selector:
    app: taskmanager-clickhouse-persistence
